### ISSUE TITLE
Project Technical Roadmap

### ISSUE THREAD

**Issue by chrisdaaz** [NUIT-CI-RCI/coldfront#9]
- [ ] Install ColdFront on `quser24`
- [ ] Connect ColdFront to a test Slurm cluster
- [ ] Add Users to ColdFront
- [ ] Add Groups to ColdFront
- [ ] Add Projects (Allocations) to ColdFront

**Comment by chrisdaaz** [comment]
We can attempt to sync the login and analytics nodes to be near-instantaneous, whereas the compute nodes could be every 15 or 20 minutes.

**Comment by chrisdaaz** [comment]
The UIDs and GIDs that Quest currently uses are different than what the ISO Authentication System uses. Moving to the ISO Authentication System would require changing permissions on every file.

We will stick to our current local authentication system (IDM) in the meantime. We should use a centralized identity management solution, which will serve as the source of truth for authentication management. This would be baked into the RHEL 8 image. This project is happening with or without ColdFront. Red Hat IDM is the same as FreeIPA. 

The FreeIPA app would check with LDAP for a match. FreeIPA manages UIDs and GIDs, which is not provided by LDAP.

**Comment by chrisdaaz** [comment]
### ColdFront-to-Quest Onboarding Process

- User logs into ColdFront
- ColdFront authenticates user via Northwestern SSO and LDAP
- ColdFront retrieves the User's NetID, Name, and Email Address and stores it in a database
- The User exists in ColdFront
- The User creates a Project or is added to a Project 
- The User creates an Allocation within a Project or is added to an Allocation within a Project
  - A plugin will retrieve Users info from ColdFront, create a Linux user on Quest (if needed), and add them to the Linux group associated with the Allocation
  - The Slurm plugin will retrieve the User's info from ColdFront (netid, email) and create a Slurm account (if needed) with any relevant associations to the Allocation
- The User may login to Quest and submit jobs

**Comment by chrisdaaz** [comment]
### File Access Management on Quest

Currently...

- Users are created with the `useradd` command executed on the Management node, which is represented as an entry in `/etc/passwd`
- Users are given access to files with the `usermod` command executed on the Management node, which is represented as an update in `/etc/group`
- The `/etc` files are sync'd across the login, analytics, klc and compute nodes several times per day

> ColdFront provides Users the ability to add and remove people from groups, which affect their file permissions. How do we approach managing permissions with simultaneous changes made to group membership?
